from __future__ import annotations

import enum
from collections.abc import Sequence

def apply(updates: Sequence[DisplayUpdate]) -> Sequence[DisplayUpdateResult]: ...
def validate(updates: Sequence[DisplayUpdate]) -> Sequence[DisplayUpdateResult]: ...
def query() -> Sequence[Display]: ...
def get(ids: Sequence[DisplayIdentifier]) -> Sequence[DisplayMatch]: ...

class DisplayMatch:
    requested_id: DisplayIdentifier
    matched_id: DisplayIdentifier
    display: Display

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class FailedDisplayUpdate:
    matched_id: DisplayIdentifier
    message: str

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class DisplayUpdateResult:
    requested_update: DisplayUpdate
    applied: Sequence[DisplayIdentifier]
    failed: Sequence[FailedDisplayUpdate]

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class DisplayIdentifier:
    name: str | None
    serial_number: str | None

    def __init__(
        self, *, name: str | None = None, serial_number: str | None = None
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class DisplayUpdate:
    id: DisplayIdentifier

    def __init__(
        self,
        id: DisplayIdentifier,
        *,
        logical: LogicalDisplayUpdateContent | None = None,
        physical: PhysicalDisplayUpdateContent | None = None,
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class LogicalDisplayUpdateContent:
    is_enabled: bool | None
    width: int | None
    height: int | None
    position: Point | None

    def __init__(
        self,
        *,
        is_enabled: bool | None = None,
        width: int | None = None,
        height: int | None = None,
        position: Point | None = None,
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PhysicalDisplayUpdateContent:
    brightness: int | None

    def __init__(self, *, brightness: int | None) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Display:
    id: DisplayIdentifier
    logical: LogicalDisplay
    physical: PhysicalDisplay | None

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Orientation(enum.Enum):
    Landscape = ...
    Portrait = ...
    LandscapeFlipped = ...
    PortraitFlipped = ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Point:
    x: int
    y: int

    def __init__(self, *, x: int, y: int) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class LogicalDisplay:
    is_enabled: bool
    orientation: Orientation
    width: int | None
    height: int | None
    position: Point | None

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PhysicalDisplay:
    brightness: int
    scale_factor: int

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
