from __future__ import annotations

from collections.abc import Sequence, Set
from typing import Any

def initialize_tracing(layer: Any) -> None: ...
def apply(updates: Sequence[DisplayUpdate]) -> Sequence[DisplayUpdate]: ...
def validate(updates: Sequence[DisplayUpdate]) -> Sequence[DisplayUpdate]: ...
def query() -> Sequence[Display]: ...
def get(ids: Set[DisplayIdentifier]) -> Sequence[Display]: ...

class DisplayIdentifier:
    name: str | None
    serial_number: str | None

    def __init__(
        self, *, name: str | None = None, serial_number: str | None = None
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class DisplayUpdate:
    id: DisplayIdentifier

    def __init__(
        self,
        id: DisplayIdentifier,
        *,
        logical: LogicalDisplayUpdateContent | None = None,
        physical: PhysicalDisplayUpdateContent | None = None,
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class LogicalDisplayUpdateContent:
    is_enabled: bool | None

    def __init__(self, *, is_enabled: bool | None) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PhysicalDisplayUpdateContent:
    brightness: int | None

    def __init__(self, *, brightness: int | None) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Display:
    id: DisplayIdentifier
    logical: LogicalDisplay
    physical: PhysicalDisplay | None

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class LogicalDisplay:
    is_enabled: bool

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class PhysicalDisplay:
    brightness: int

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
